/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointegrador.poliedro.telas;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import projetointegrador.poliedro.modelo.Serie;
import projetointegrador.poliedro.modelo.Usuario;
import projetointegrador.poliedro.persistencia.DAO;
import projetointegrador.poliedro.persistencia.UsuarioDAO;

/**
 *
 * @author mathe
 */
public class CadastroUsuariosTela extends javax.swing.JFrame {
    
    private void obterSeries() {
        try {
            var dao = new DAO();
            var series = dao.obterSeries();
            selecionarSerieComboBox.setModel(
                    new DefaultComboBoxModel<Serie>(series.toArray(new Serie[1]))
            );

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lista de séries indisponível");
        }
    }
    public CadastroUsuariosTela() {
       super("Rumo ao topo - Poliedro"); //Configura o título da tela 
       initComponents();
       obterSeries();
       this.setResizable(false); 
       this.setMaximizedBounds(this.getBounds()); 
       setLocationRelativeTo(null); //centraliza a tela quando ela aparece
       
        emailTextField.setText("Digite o email");
        emailTextField.setForeground(Color.GRAY);

        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (emailTextField.getText().equals("Digite o email")) {
                    emailTextField.setText("");
                    emailTextField.setForeground(Color.BLACK);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (emailTextField.getText().isEmpty()) {
                    emailTextField.setForeground(Color.GRAY);
                    emailTextField.setText("Digite o email");
                }
            }
            
        });
        nomeTextField.setText("Digite o nome");
        nomeTextField.setForeground(Color.GRAY);

        nomeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (nomeTextField.getText().equals("Digite o nome")) {
                    nomeTextField.setText("");
                    nomeTextField.setForeground(Color.BLACK);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (nomeTextField.getText().isEmpty()) {
                    nomeTextField.setForeground(Color.GRAY);
                    nomeTextField.setText("Digite o nome");
                }
            }
        });
        // Placeholder para senhaPasswordField
        senhaPasswordField.setText("Digite a senha");
        senhaPasswordField.setForeground(Color.GRAY);
        senhaPasswordField.setEchoChar((char) 0); // mostra o texto normalmente

        senhaPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (String.valueOf(senhaPasswordField.getPassword()).equals("Digite a senha")) {
                    senhaPasswordField.setText("");
                    senhaPasswordField.setForeground(Color.BLACK);
                    senhaPasswordField.setEchoChar('•'); // ou '*'
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (senhaPasswordField.getPassword().length == 0) {
                    senhaPasswordField.setForeground(Color.GRAY);
                    senhaPasswordField.setText("Digite a senha");
                    senhaPasswordField.setEchoChar((char) 0);
                }
            }
        });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        senhaPasswordField = new javax.swing.JPasswordField();
        cadastrarButton = new javax.swing.JButton();
        selecionarSerieComboBox = new javax.swing.JComboBox<>();
        voltarButton = new javax.swing.JButton();
        telaCadastroLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        nomeTextField.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        nomeTextField.setToolTipText("");
        nomeTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextField);
        nomeTextField.setBounds(350, 260, 350, 40);

        emailTextField.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        emailTextField.setToolTipText("");
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField);
        emailTextField.setBounds(350, 310, 350, 40);

        senhaPasswordField.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        senhaPasswordField.setBorder(null);
        senhaPasswordField.setOpaque(true);
        senhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaPasswordField);
        senhaPasswordField.setBounds(350, 360, 350, 40);

        cadastrarButton.setBorderPainted(false);
        cadastrarButton.setContentAreaFilled(false);
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarButton);
        cadastrarButton.setBounds(350, 450, 350, 50);

        selecionarSerieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Serie[] {
            new Serie(1, "1° Ano"),
            new Serie(2, "2° Ano"), 
            new Serie(3, "3° Ano")
        }));
        selecionarSerieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarSerieComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(selecionarSerieComboBox);
        selecionarSerieComboBox.setBounds(450, 410, 150, 30);

        voltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoVoltarPequeno.png"))); // NOI18N
        voltarButton.setText("jButton1");
        voltarButton.setBorderPainted(false);
        voltarButton.setContentAreaFilled(false);
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton);
        voltarButton.setBounds(10, 630, 110, 30);

        telaCadastroLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/FundoCadastroBotao.png"))); // NOI18N
        getContentPane().add(telaCadastroLabel);
        telaCadastroLabel.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaPasswordFieldActionPerformed

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        try{
            String nome = nomeTextField.getText();
            String email = emailTextField.getText();
            String senha = new String(senhaPasswordField.getPassword());
            Serie serieSelecionada = (Serie) selecionarSerieComboBox.getSelectedItem();
            int codigo = serieSelecionada.getCodigo(); // Obterá 1, 2 ou 3
            if(nome.isEmpty() || email.isEmpty() || senha.isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
                return ; 
            }
            if (serieSelecionada == null){
                JOptionPane.showMessageDialog(null, "Selecione uma série");
                return;
            }
            var usuario = new Usuario(nome, email, senha, serieSelecionada.getCodigo());
            
            var usuarioDAO = new UsuarioDAO();
            usuarioDAO.cadastrar(usuario);
            
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!!");
        }
        catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar usuário");
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void selecionarSerieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarSerieComboBoxActionPerformed
        
    }//GEN-LAST:event_selecionarSerieComboBoxActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        var mu = new TelaCRUDusuarios();
        mu.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuariosTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JComboBox<Serie> selecionarSerieComboBox;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JLabel telaCadastroLabel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
