/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointegrador.poliedro.telas;

/**
 *
 * @author mathe
 */
public class PontuacaoFinalTela extends javax.swing.JFrame {

    public PontuacaoFinalTela() {
        super("Rumo ao topo - Poliedro"); //Configura o título da tela 
        initComponents();
        this.setResizable(false); 
        this.setMaximizedBounds(this.getBounds()); 
        setLocationRelativeTo(null); //centraliza a tela quando ela aparece
        questoesRespondidasTextField.setBackground(new java.awt.Color(0, 0, 0, 0));
        acertosTextField.setBackground(new java.awt.Color(0, 0, 0, 0));
        dinheiroGanhoTextField.setBackground(new java.awt.Color(0, 0, 0, 0));
        materiaTextField.setBackground(new java.awt.Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questoesRespondidasTextField = new javax.swing.JTextField();
        materiaTextField = new javax.swing.JTextField();
        dinheiroGanhoTextField = new javax.swing.JTextField();
        acertosTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        questoesRespondidasTextField.setEditable(false);
        questoesRespondidasTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        questoesRespondidasTextField.setForeground(new java.awt.Color(255, 255, 255));
        questoesRespondidasTextField.setText("9");
        questoesRespondidasTextField.setBorder(null
        );
        questoesRespondidasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questoesRespondidasTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(questoesRespondidasTextField);
        questoesRespondidasTextField.setBounds(750, 350, 150, 50);

        materiaTextField.setEditable(false);
        materiaTextField.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        materiaTextField.setForeground(new java.awt.Color(255, 255, 255));
        materiaTextField.setText("Matematica");
        materiaTextField.setBorder(null);
        materiaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(materiaTextField);
        materiaTextField.setBounds(660, 260, 240, 50);

        dinheiroGanhoTextField.setEditable(false);
        dinheiroGanhoTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dinheiroGanhoTextField.setForeground(new java.awt.Color(255, 255, 255));
        dinheiroGanhoTextField.setText("780.000");
        dinheiroGanhoTextField.setBorder(null);
        getContentPane().add(dinheiroGanhoTextField);
        dinheiroGanhoTextField.setBounds(700, 520, 150, 50);

        acertosTextField.setEditable(false);
        acertosTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        acertosTextField.setForeground(new java.awt.Color(255, 255, 255));
        acertosTextField.setText("8");
        acertosTextField.setBorder(null);
        getContentPane().add(acertosTextField);
        acertosTextField.setBounds(750, 440, 150, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoAvançar.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(900, 630, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/FundoTelaPontuacaoFinal.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questoesRespondidasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questoesRespondidasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questoesRespondidasTextFieldActionPerformed

    private void materiaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materiaTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        var jn = new JogarNovamenteTela();
        jn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PontuacaoFinalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PontuacaoFinalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PontuacaoFinalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PontuacaoFinalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PontuacaoFinalTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acertosTextField;
    private javax.swing.JTextField dinheiroGanhoTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField materiaTextField;
    private javax.swing.JTextField questoesRespondidasTextField;
    // End of variables declaration//GEN-END:variables
}
