/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointegrador.poliedro.telas;

/**
 *
 * @author mathe
 */
public class TelaCRUDperguntas extends javax.swing.JFrame {

    /**
     * Creates new form TelaCRUDperguntas
     */
    public TelaCRUDperguntas() {
        super("Rumo ao topo - Poliedro"); //Configura o título da tela 
        initComponents();
        this.setResizable(false); 
        this.setMaximizedBounds(this.getBounds()); 
        setLocationRelativeTo(null); //centraliza a tela quando ela aparece
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adicionarPerguntasButton = new javax.swing.JButton();
        consultarPerguntasButton = new javax.swing.JButton();
        excluirPerguntasButton = new javax.swing.JButton();
        editarPerguntasButton = new javax.swing.JButton();
        botaoVoltarButton = new javax.swing.JButton();
        fundoCRUDperguntasLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        adicionarPerguntasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoAdicionarPerguntas (1).png"))); // NOI18N
        adicionarPerguntasButton.setBorderPainted(false);
        adicionarPerguntasButton.setContentAreaFilled(false);
        adicionarPerguntasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPerguntasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(adicionarPerguntasButton);
        adicionarPerguntasButton.setBounds(250, 350, 280, 70);

        consultarPerguntasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoConsultarPerguntas (1).png"))); // NOI18N
        consultarPerguntasButton.setBorderPainted(false);
        consultarPerguntasButton.setContentAreaFilled(false);
        consultarPerguntasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPerguntasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(consultarPerguntasButton);
        consultarPerguntasButton.setBounds(250, 450, 280, 70);

        excluirPerguntasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoExcluirPerguntas (1).png"))); // NOI18N
        excluirPerguntasButton.setBorderPainted(false);
        excluirPerguntasButton.setContentAreaFilled(false);
        getContentPane().add(excluirPerguntasButton);
        excluirPerguntasButton.setBounds(560, 450, 280, 70);

        editarPerguntasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoEditarPerguntas (2).png"))); // NOI18N
        editarPerguntasButton.setBorderPainted(false);
        editarPerguntasButton.setContentAreaFilled(false);
        getContentPane().add(editarPerguntasButton);
        editarPerguntasButton.setBounds(560, 350, 280, 70);

        botaoVoltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoVoltarPequeno.png"))); // NOI18N
        botaoVoltarButton.setBorderPainted(false);
        botaoVoltarButton.setContentAreaFilled(false);
        botaoVoltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltarButton);
        botaoVoltarButton.setBounds(10, 630, 110, 30);

        fundoCRUDperguntasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/FundoDemaisTelasArrumado.png"))); // NOI18N
        getContentPane().add(fundoCRUDperguntasLabel);
        fundoCRUDperguntasLabel.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarPerguntasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPerguntasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarPerguntasButtonActionPerformed

    private void adicionarPerguntasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPerguntasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarPerguntasButtonActionPerformed

    private void botaoVoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarButtonActionPerformed
        var so = new TelaSelecionarOpcaoProfessor();
        so.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoVoltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDperguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDperguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDperguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDperguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCRUDperguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarPerguntasButton;
    private javax.swing.JButton botaoVoltarButton;
    private javax.swing.JButton consultarPerguntasButton;
    private javax.swing.JButton editarPerguntasButton;
    private javax.swing.JButton excluirPerguntasButton;
    private javax.swing.JLabel fundoCRUDperguntasLabel;
    // End of variables declaration//GEN-END:variables
}
