/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointegrador.poliedro.telas;

/**
 *
 * @author Lucas C Ribeiro
 */
public class TelaSelecionarMateria extends javax.swing.JFrame {

    /**
     * Creates new form TelaSelecionarMateria
     */
    public TelaSelecionarMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matematicaButton = new javax.swing.JButton();
        geometriaButton = new javax.swing.JButton();
        portuguesButton = new javax.swing.JButton();
        biologiaButton = new javax.swing.JButton();
        quimicaButton = new javax.swing.JButton();
        fisicaButton = new javax.swing.JButton();
        geografiaButton = new javax.swing.JButton();
        historiaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 960));
        setMinimumSize(new java.awt.Dimension(1440, 960));
        getContentPane().setLayout(null);

        matematicaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoMatematica.png"))); // NOI18N
        matematicaButton.setBorderPainted(false);
        matematicaButton.setContentAreaFilled(false);
        matematicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matematicaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(matematicaButton);
        matematicaButton.setBounds(100, 570, 310, 80);

        geometriaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoGeometria.png"))); // NOI18N
        geometriaButton.setText("jButton1");
        geometriaButton.setBorderPainted(false);
        geometriaButton.setContentAreaFilled(false);
        getContentPane().add(geometriaButton);
        geometriaButton.setBounds(560, 570, 320, 90);

        portuguesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoPortugues.png"))); // NOI18N
        portuguesButton.setText("jButton2");
        portuguesButton.setBorderPainted(false);
        portuguesButton.setContentAreaFilled(false);
        getContentPane().add(portuguesButton);
        portuguesButton.setBounds(1000, 570, 320, 90);

        biologiaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoBiologia.png"))); // NOI18N
        biologiaButton.setBorderPainted(false);
        biologiaButton.setContentAreaFilled(false);
        getContentPane().add(biologiaButton);
        biologiaButton.setBounds(100, 680, 310, 80);

        quimicaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoQuimica.png"))); // NOI18N
        quimicaButton.setBorderPainted(false);
        quimicaButton.setContentAreaFilled(false);
        getContentPane().add(quimicaButton);
        quimicaButton.setBounds(560, 680, 310, 90);

        fisicaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoFisica.png"))); // NOI18N
        fisicaButton.setText("jButton1");
        fisicaButton.setBorderPainted(false);
        fisicaButton.setContentAreaFilled(false);
        getContentPane().add(fisicaButton);
        fisicaButton.setBounds(1000, 680, 320, 90);

        geografiaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoGeografia.png"))); // NOI18N
        geografiaButton.setText("jButton1");
        geografiaButton.setBorderPainted(false);
        geografiaButton.setContentAreaFilled(false);
        geografiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geografiaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(geografiaButton);
        geografiaButton.setBounds(100, 790, 320, 80);

        historiaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoHistoria.png"))); // NOI18N
        historiaButton.setText("jButton1");
        historiaButton.setBorderPainted(false);
        historiaButton.setContentAreaFilled(false);
        getContentPane().add(historiaButton);
        historiaButton.setBounds(560, 790, 320, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/TelaSelecionarMateriaAluno.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 1360, 1030);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matematicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matematicaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matematicaButtonActionPerformed

    private void geografiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geografiaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geografiaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSelecionarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSelecionarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSelecionarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSelecionarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSelecionarMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton biologiaButton;
    private javax.swing.JButton fisicaButton;
    private javax.swing.JButton geografiaButton;
    private javax.swing.JButton geometriaButton;
    private javax.swing.JButton historiaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton matematicaButton;
    private javax.swing.JButton portuguesButton;
    private javax.swing.JButton quimicaButton;
    // End of variables declaration//GEN-END:variables
}
