/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointegrador.poliedro.telas;

import javax.swing.JOptionPane;
import projetointegrador.poliedro.modelo.Usuario;
import projetointegrador.poliedro.persistencia.DAO;

/**
 *
 * @author mathe
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin
     */
    public TelaLogin() {
        super("Rumo ao topo - Poliedro"); //Configura o título da tela 
        initComponents();
        this.setResizable(false); 
        this.setMaximizedBounds(this.getBounds()); 
        setLocationRelativeTo(null); //centraliza a tela quando ela aparece
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sairButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        inserirEmailTextField = new javax.swing.JTextField();
        inserirSenhaPasswordField = new javax.swing.JPasswordField();
        fundoTelaLoginJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 960));
        setResizable(false);
        getContentPane().setLayout(null);

        sairButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/BotaoSairDemaisTelas.png"))); // NOI18N
        sairButton.setBorderPainted(false);
        sairButton.setContentAreaFilled(false);
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton);
        sairButton.setBounds(10, 875, 80, 30);

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/botaologin.png"))); // NOI18N
        loginButton.setToolTipText("");
        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.setMaximumSize(new java.awt.Dimension(60, 20));
        loginButton.setMinimumSize(new java.awt.Dimension(60, 20));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(545, 540, 350, 40);

        inserirEmailTextField.setMaximumSize(new java.awt.Dimension(60, 20));
        inserirEmailTextField.setMinimumSize(new java.awt.Dimension(60, 20));
        inserirEmailTextField.setPreferredSize(new java.awt.Dimension(60, 20));
        inserirEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirEmailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(inserirEmailTextField);
        inserirEmailTextField.setBounds(545, 440, 350, 40);

        inserirSenhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirSenhaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(inserirSenhaPasswordField);
        inserirSenhaPasswordField.setBounds(545, 490, 350, 40);

        fundoTelaLoginJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/TelaLogin.png"))); // NOI18N
        getContentPane().add(fundoTelaLoginJLabel);
        fundoTelaLoginJLabel.setBounds(0, 0, 1440, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirEmailTextFieldActionPerformed

    private void inserirSenhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirSenhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirSenhaPasswordFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
     try{
            var email = inserirEmailTextField.getText();
            var senha = new String(inserirSenhaPasswordField.getPassword());
            var user = new Usuario(email, senha);
            //2. Construir um objeto DAO 
            var dao = new DAO();
            if (dao.existe(user)) {
                String tipo = dao.obterTipo(user);  //verifica o tipo do usuario (professor ou aluno)
                if ("professor".equalsIgnoreCase(tipo)) {
                    TelaSelecionarOpcaoProfessor opcao = new TelaSelecionarOpcaoProfessor();
                    opcao.setVisible(true);
                    this.dispose();
                } else {
                    TelaSelecionarSerie serie = new TelaSelecionarSerie();
                    serie.setVisible(true); 
                    this.dispose(); // se for aluno direciona para a tela de selecionar serie
                    
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário/Senha inválido(s)");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Sistema indisponível");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundoTelaLoginJLabel;
    private javax.swing.JTextField inserirEmailTextField;
    private javax.swing.JPasswordField inserirSenhaPasswordField;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
