/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointegrador.poliedro.telas;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel salve
 */
public class TelaPergunta extends javax.swing.JFrame {

    /**
     * Creates new form TelaPergunta
     */
    public TelaPergunta() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void aplicarDica5050() {
        JButton[] alternativas = {alternativa1, alternativa2, alternativa3, alternativa4, alternativa5};

        int indiceCorreta = 0; // A primeira é a correta (índice 0)

        java.util.List<Integer> erradas = new java.util.ArrayList<>();
        for (int i = 0; i < alternativas.length; i++) {
            if (i != indiceCorreta) {
                erradas.add(i);
            }
        }

        java.util.Collections.shuffle(erradas);
        int erradaParaManter = erradas.remove(0);

        for (int i : erradas) {
            alternativas[i].setEnabled(false);
            alternativas[i].setVisible(false); // ou só setEnabled(false)
        }

        dica5050.setEnabled(false);
    }

    


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        alternativa1 = new javax.swing.JButton();
        alternativa4 = new javax.swing.JButton();
        alternativa2 = new javax.swing.JButton();
        alternativa3 = new javax.swing.JButton();
        alternativa5 = new javax.swing.JButton();
        dica5050 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Qual é a capital do Brasil?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 30, 670, 110);

        alternativa1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alternativa1.setForeground(new java.awt.Color(255, 255, 255));
        alternativa1.setText("Brasília");
        alternativa1.setBorderPainted(false);
        alternativa1.setContentAreaFilled(false);
        alternativa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa1ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa1);
        alternativa1.setBounds(190, 190, 340, 70);

        alternativa4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alternativa4.setForeground(new java.awt.Color(255, 255, 255));
        alternativa4.setText("Salvador");
        alternativa4.setBorderPainted(false);
        alternativa4.setContentAreaFilled(false);
        alternativa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa4ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa4);
        alternativa4.setBounds(190, 470, 340, 80);

        alternativa2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alternativa2.setForeground(new java.awt.Color(255, 255, 255));
        alternativa2.setText("São Paulo");
        alternativa2.setBorderPainted(false);
        alternativa2.setContentAreaFilled(false);
        alternativa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa2ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa2);
        alternativa2.setBounds(190, 280, 340, 80);

        alternativa3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alternativa3.setForeground(new java.awt.Color(255, 255, 255));
        alternativa3.setText("Rio de Janeiro");
        alternativa3.setBorderPainted(false);
        alternativa3.setContentAreaFilled(false);
        alternativa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa3ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa3);
        alternativa3.setBounds(190, 380, 340, 70);

        alternativa5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alternativa5.setForeground(new java.awt.Color(255, 255, 255));
        alternativa5.setText("Belo Horizonte");
        alternativa5.setBorderPainted(false);
        alternativa5.setContentAreaFilled(false);
        alternativa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa5ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa5);
        alternativa5.setBounds(190, 570, 340, 70);

        dica5050.setBorderPainted(false);
        dica5050.setContentAreaFilled(false);
        dica5050.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dica5050ActionPerformed(evt);
            }
        });
        getContentPane().add(dica5050);
        dica5050.setBounds(640, 340, 100, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/poliedro/teste/imagem/folder/TelaPerguntas.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alternativa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa1ActionPerformed
        JOptionPane.showMessageDialog(null, "Resposta Correta! Próxima pergunta!");
    }//GEN-LAST:event_alternativa1ActionPerformed

    private void alternativa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa2ActionPerformed
        JOptionPane.showMessageDialog(null, "Resposta errada!");
    }//GEN-LAST:event_alternativa2ActionPerformed

    private void alternativa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa3ActionPerformed
        JOptionPane.showMessageDialog(null, "Resposta errada!");
    }//GEN-LAST:event_alternativa3ActionPerformed

    private void alternativa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa4ActionPerformed
        JOptionPane.showMessageDialog(null, "Resposta errada!");
    }//GEN-LAST:event_alternativa4ActionPerformed

    private void alternativa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa5ActionPerformed
        JOptionPane.showMessageDialog(null, "Resposta errada!");
    }//GEN-LAST:event_alternativa5ActionPerformed

    private void dica5050ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dica5050ActionPerformed
        aplicarDica5050();
    }//GEN-LAST:event_dica5050ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPergunta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alternativa1;
    private javax.swing.JButton alternativa2;
    private javax.swing.JButton alternativa3;
    private javax.swing.JButton alternativa4;
    private javax.swing.JButton alternativa5;
    private javax.swing.JButton dica5050;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
